dq-ReviewBackend get by user endpoint + tests
ucsb-cs156-f24/proj-dining-f24-13 pull request #47
Opened 2024-11-22 22:01 UTC by st4lemon

Closes #12 

Go to https://dining-st4lemon.dokku-13.cs.ucsb.edu 

WIP

2024-11-23 19:53 UTC, clevermonkey16 commented
Seems like the dokku database might not be working
<img width="1381" alt="Screenshot 2024-11-23 at 11 52 32 AM" src="https://github.com/user-attachments/assets/58a41d16-a4ce-4b9f-b2e1-1d99456d0887">

2024-11-24 09:11 UTC, st4lemon commented
> Seems like the dokku database might not be working <img alt="Screenshot 2024-11-23 at 11 52 32 AM" width="1381" src="https://private-user-images.githubusercontent.com/114888478/389223143-58a41d16-a4ce-4b9f-b2e1-1d99456d0887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0Mzk3MTIsIm5iZiI6MTczMjQzOTQxMiwicGF0aCI6Ii8xMTQ4ODg0NzgvMzg5MjIzMTQzLTU4YTQxZDE2LWE0Y2UtNGI5Zi1iMmUxLTFkOTk0NTZkMDg4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQwOTEwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODYyMGNmMmJkMGIyODM1ZDU5Yzc3Mjg0MGI5ZjgwZTU5NDI4MmFiMzBmNGRiNjg4ZTU0MDM1ZDk0Y2NmMDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-JCmvC4V-lrZnmvg94MEYFCKjCvkk4efSVhLDVF60DI">

seems like postgres database was broken for some reason. issue should be fixed, I set up a new database and tested it again.

2024-11-25 00:15 UTC, clevermonkey16 approved these changes
LGTM, works on dokku

2024-11-25 02:29 UTC, pconrad requested changes
The two new methods LGTM, but this needs to be adjusted for the Code Review feedback on #46

2024-11-25 02:29 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/ReviewsController.java
> +     */
See Code Review feedback on #46 and apply it to the post method below as well

2024-11-25 07:36 UTC, pconrad approved these changes
LGTM

2024-11-25 07:39 UTC, merged