Shivanimadhan meals endpoint (just to see what changed)
ucsb-cs156-f24/proj-dining-f24-13 pull request #53
Opened 2024-11-25 17:46 UTC by clevermonkey16

2024-11-27 07:59 UTC, emiz39 submitted a review, later dismissed
getDays is not working on swagger

2024-11-27 08:06 UTC, shivanimadhan commented
Swagger is working on localhost but not on dokku

2024-11-28 00:46 UTC, pconrad requested changes
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-11-28 00:46 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/DiningMenuAPIController.java
> +  // }
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-11-29 04:53 UTC, Anteater10 commented
LGTM

2024-11-30 22:03 UTC, pconrad approved these changes
LGTM

2024-11-30 22:03 UTC, merged